---
language: python

dist: bionic

os:
  - linux

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y bro

script:
  - bro -Cr tests/http_post.trace -b scripts/main.bro
  - egrep "username[1-5]" http.log |wc -l |grep -q 5
  - egrep "username[1-5]" notice.log |wc -l |grep -q 5
